#!/bin/tcsh -f

# CMSC 216, Fall 2017, Project #13
# Public test 3 (public3)
#
# Tests the program with two filenames on the command line, so two threads
# will be created.  The files have many numbers.
#
# (c) Larry Herman, 2017.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./sum-files-threaded.x public3a.input public3b.input
